// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ViDbgl2CzbxmVwZCmkLbJKKn8KxWc50',
    appId: '1:1011564574387:web:16eac4a9611872cf78a2c6',
    messagingSenderId: '1011564574387',
    projectId: 'house-cleaning-cf165',
    authDomain: 'house-cleaning-cf165.firebaseapp.com',
    storageBucket: 'house-cleaning-cf165.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnyDwq9hNkog7UTsaiIKzR93THwj2CNl0',
    appId: '1:1011564574387:android:d5c427d910de373378a2c6',
    messagingSenderId: '1011564574387',
    projectId: 'house-cleaning-cf165',
    storageBucket: 'house-cleaning-cf165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9FHc3UrudVK3c-Tm31SM8TvVewPNoIJI',
    appId: '1:1011564574387:ios:1aa79681ead6d95778a2c6',
    messagingSenderId: '1011564574387',
    projectId: 'house-cleaning-cf165',
    storageBucket: 'house-cleaning-cf165.firebasestorage.app',
    iosBundleId: 'com.example.houseCleaning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9FHc3UrudVK3c-Tm31SM8TvVewPNoIJI',
    appId: '1:1011564574387:ios:1aa79681ead6d95778a2c6',
    messagingSenderId: '1011564574387',
    projectId: 'house-cleaning-cf165',
    storageBucket: 'house-cleaning-cf165.firebasestorage.app',
    iosBundleId: 'com.example.houseCleaning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ViDbgl2CzbxmVwZCmkLbJKKn8KxWc50',
    appId: '1:1011564574387:web:e54a6074b81eeb5d78a2c6',
    messagingSenderId: '1011564574387',
    projectId: 'house-cleaning-cf165',
    authDomain: 'house-cleaning-cf165.firebaseapp.com',
    storageBucket: 'house-cleaning-cf165.firebasestorage.app',
  );
}
